### ISSUE TITLE
Possibility to set up highlight.js style in _config.yml

### ISSUE THREAD

**Issue by pavdmyt** [kronik3r/daktilo#11]
I found that `/assets/vendor/highlight/styles/` contains all styles supported by _highlight.js_. It would be good to add possibility to manually choose style for syntax highlighting in `_config.yml`. Otherwise, why we need all available styles in our assets?

**Comment by kronik3r** [comment]
Hi, yeah you're right that was the plan actually, to be able to change the style from the configuration file but I didn't get the chance to do it, probably I will work on it this week-end and thank you for the reminder :+1:
