### ISSUE TITLE
Implement disqus comments system

### ISSUE THREAD

**Issue by ismnoiet** [kronik3r/daktilo#18]
Hi, first of all thank you for this theme.
Second, how to implement disqus comments system with this theme ?, i've tried :
- Register my website with disqus.
- Add `disqus: my_disqus_username` property  to the `_config.yml` file .
- Add `comments: true` to every post located under __posts_ folder.

And i'm not getting the expected result.

**Comment by ismnoiet** [comment]
Now everything is working, closed  issue :)

**Comment by kronik3r** [comment]
Hey @ismnoiet sorry for the late reply, glade you fixed the issue :D, was it from your end or it's an issue with Daktilo?

**Comment by ismnoiet** [comment]
I think it was because of the comment below the file `_config.yml` that says 
`# disqus: your_disqus_username` therefore i tried to use my _disqus username_.
BUT what you wanted to say(i think) is **the unique Disqus URL associated with the current website** :).

**Comment by kronik3r** [comment]
Ah I see :D that's very confusing I gotta say :D thanks, I will fix that comment right away.

**Comment by hamism** [comment]
:+1:

**Comment by ismnoiet** [comment]
:+1:
