### ISSUE TITLE
Update Jekyllthemes.org theme page info

### ISSUE THREAD

**Issue by kronik3r** [kronik3r/daktilo#22]
The page of the theme still links to the old demo website, see [link](http://jekyllthemes.org/themes/daktilo/) for more info.

**Comment by anshulxyz** [comment]
The pull-request has been merged, [see here](https://github.com/mattvh/jekyllthemes/pull/441) and now the demo is directed to [http://electrik-frog.com/daktilo/](http://electrik-frog.com/daktilo/)
